name: PROG CI/CD


on:

 push:


jobs:

 PROG-RUN-PYTHON:

  runs-on: ubuntu-latest


  steps:

   - name: Download repository

    uses: actions/checkout@v6


   - name: Set up Python

    uses: actions/setup-python@v5

    with:

     python-version: "3.12"


   - name: Run program

    run: python3 69051238.py